[2023-11-15T09:14:40.994+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_projet.transform_and_load manual__2023-11-15T09:14:36.905085+00:00 [queued]>
[2023-11-15T09:14:40.997+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_projet.transform_and_load manual__2023-11-15T09:14:36.905085+00:00 [queued]>
[2023-11-15T09:14:40.997+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-15T09:14:41.003+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform_and_load> on 2023-11-15 09:14:36.905085+00:00
[2023-11-15T09:14:41.007+0000] {standard_task_runner.py:57} INFO - Started process 1503 to run task
[2023-11-15T09:14:41.009+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_projet', 'transform_and_load', 'manual__2023-11-15T09:14:36.905085+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/ETL_projet.py', '--cfg-path', '/tmp/tmp2yegma2j']
[2023-11-15T09:14:41.010+0000] {standard_task_runner.py:85} INFO - Job 77: Subtask transform_and_load
[2023-11-15T09:14:41.031+0000] {task_command.py:416} INFO - Running <TaskInstance: ETL_projet.transform_and_load manual__2023-11-15T09:14:36.905085+00:00 [running]> on host 48045a1653b9
[2023-11-15T09:14:41.061+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='a***' AIRFLOW_CTX_DAG_ID='ETL_projet' AIRFLOW_CTX_TASK_ID='transform_and_load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-15T09:14:36.905085+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-15T09:14:36.905085+00:00'
[2023-11-15T09:14:41.075+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-15T09:14:41.108+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-15T09:14:41.124+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DependentObjectsStillExist: cannot drop table departments_region because other objects depend on it
DETAIL:  constraint urgences_covid_dep_fkey on table urgences_covid depends on table departments_region
HINT:  Use DROP ... CASCADE to drop the dependent objects too.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL_projet.py", line 39, in data_transform
    cleaned_df_dept.to_sql('departments_region', postgres_sql_upload.get_sqlalchemy_engine(), if_exists='replace', chunksize=1000)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2878, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 769, in to_sql
    return pandas_sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1910, in to_sql
    table = self.prep_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1814, in prep_table
    table.create()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 907, in create
    self.pd_sql.drop_table(self.name, self.schema)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1963, in drop_table
    self.get_table(table_name, schema).drop(bind=self.con)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 979, in drop
    bind._run_ddl_visitor(ddl.SchemaDropper, self, checkfirst=checkfirst)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2221, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 1106, in visit_table
    self.connection.execute(DropTable(table))
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1477, in _execute_ddl
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop table departments_region because other objects depend on it
DETAIL:  constraint urgences_covid_dep_fkey on table urgences_covid depends on table departments_region
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL: 
DROP TABLE departments_region]
(Background on this error at: https://sqlalche.me/e/14/2j85)
[2023-11-15T09:14:41.132+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=ETL_projet, task_id=transform_and_load, execution_date=20231115T091436, start_date=20231115T091440, end_date=20231115T091441
[2023-11-15T09:14:41.139+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 77 for task transform_and_load ((psycopg2.errors.DependentObjectsStillExist) cannot drop table departments_region because other objects depend on it
DETAIL:  constraint urgences_covid_dep_fkey on table urgences_covid depends on table departments_region
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL: 
DROP TABLE departments_region]
(Background on this error at: https://sqlalche.me/e/14/2j85); 1503)
[2023-11-15T09:14:41.187+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-15T09:14:41.201+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
